site_name: Forta Developer SDK

nav:
  - Overview: index.md
  - Build your first agent:
      - 1) Quick start: quickstart.md
      - 2) Testing your agent: testing.md
      - 3) Deploying your agent: deploying.md
      - 4) Subscribing to alerts: subscribing.md
      - 5) Maintaining your agent: maintaining.md
  - Video tutorials: tutorials.md
  - Reference:
      - Core concepts: concepts.md
      - CLI commands: cli.md
      - forta.config.json: config.md
  - Javascript/Typescript SDK: sdk.md
  - Python SDK: python.md
  - Agent patterns:
      - Storing sensitive data: sensitive-data.md
      - Private alerts: private-alerts.md
      - Long running tasks: longrunning-tasks.md
      - Querying other chains: querying-chains.md
      - Transaction simulation: tx-simulation.md
      - Error monitoring: error-monitoring.md
  - Best practices: best-practices.md
  - Data science and machine learning on Forta: ds-and-ml.md
  - Getting help: help.md
  - FAQ: faq.md
  - How to contribute: contributing.md
  - Useful libraries: useful-libraries.md
  - Agent Developer Contests:
      - Compound Contest (10/20/2021): contest1-compound.md
      - Aave Contest (11/3/2021): contest2-aave.md
      - OpenZeppelin Contest (11/18/2021): contest3-oz.md
      - Forta Contest (12/17/2021): contest4-forta.md

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: blue grey
  logo: forta-logo.png
  favicon: forta-logo.png
  features:
    - navigation.expand
    - navigation.instant

extra:
  analytics:
    provider: custom
    gtmId: GTM-WNVX2Q6

markdown_extensions:
  - admonition
