site_name: Forta Docs

nav:
  - <strong>Firewall</strong>:
      - What is Forta Firewall?: what-is-forta-firewall.md
      - Why Transaction Screening: why-transaction-screening.md
      - FORTRESS - AI Based Risk Scoring: FORTRESS-ai-based-risk-scoring.md
      - Forta Chain: fota-chain.md
  - <strong>FORTA Overview</strong>:
      - Tokenomics: fort-token.md
      - Governance: governance.md
      - FAQs: FAQs.md
      - Security Overview:
          - Intro: security.md
          - Design: security-design.md
          - Development: security-develop.md
          - Deployment & Smart Contracts: security-deploy.md
          - Testing and Review: security-testing.md
          - Maintenance: security-maintain.md
          - Smart Contracts:
              - Intro: smart-contracts.md
              - Access Manager: contracts/components/access/AccessManager.md
              - Agent Registry: contracts/components/agents/AgentRegistry.md
              - Dispatch: contracts/components/dispatch/Dispatch.md
              - Meta-transaction: contracts/components/metatx/Forwarder.md
              - Scanner Pool Registry: contracts/components/scanner_pools/ScannerPoolRegistry.md
              - Scanner Registry: contracts/components/scanners/ScannerRegistry.md
              - Scanner To Scanner Pool Migration: contracts/components/scanners/ScannerToNodeRunnerMigration.md
              - Staking:
                  - Allocation:
                      - Stake Allocator: contracts/components/staking/StakeAllocator.md
                  - Rewards:
                      - Accumulators: contracts/components/staking/Accumulators.md
                      - Rewards Distributor: contracts/components/staking/RewardsDistributor.md
                  - Slashing:
                      - Slashing Controller: contracts/components/staking/SlashingController.md
                      - Slash Reasons: contracts/components/staking/SlashReasons.md
                  - Stake Subjects:
                      - Delegated Stake Subject: contracts/components/staking/DelegatedStakeSubject.md
                      - Direct Stake Subject: contracts/components/staking/DirectStakeSubject.md
                      - Stake Subject Gateway: contracts/components/staking/StakeSubjectGateway.md
                  - Forta Staking: contracts/components/staking/FortaStaking.md
                  - Forta Staking Utils: contracts/components/staking/FortaStakingUtils.md
                  - Subject Type Validator: contracts/components/staking/SubjectTypeValidator.md
              - Utils:
                  - Access Managed: contracts/components/utils/AccessManaged.md
                  - Forwarded Context: contracts/components/utils/ForwardedContext.md
                  - Reentrancy Guard Handler: contracts/components/utils/ReentrancyGuardHandler.md
                  - Routed: contracts/components/utils/Routed.md
                  - State Machines: contracts/components/utils/StateMachines.md
              - Base Component Upgradeable: contracts/components/BaseComponentUpgradeable.md
              - Roles: contracts/components/Roles.md
          - Stake Slashing:
              - Slashing Policy: slashing-policy.md
              - Creating a Slash Proposal: slashing-creating-proposal.md
  - <strong>Staking on Forta</strong>:
      - Delegated staking:
          - Introduction: delegated-staking-introduction.md
          - Rewards: delegated-staking-rewards.md
      - FORT Holder Staking Guide: fort-holder-staking-guide.md
      - FORT Vault Deposit Guide: deposit-fort-vault.md
      - Direct withdrawal: scanner-direct-withdrawal.md     
  - <strong>Monitoring Network</strong>:
      - Getting Started: getting-started.md
      - Introduction to Subscription Tiers: introduction-to-subscription-tiers.md
      - Using the API: api-reference.md
      - GraphQL Reference: forta-api-reference/index.html
      - Subscribing to a bot: subscribing-to-bot.md
      - Use Cases: https://forta.notion.site/Selected-Use-Cases-1dcdf290ecfb47788cd588cdfa12585c
      - Tutorial - How to pay for Forta: fees-tut-how-pay.md
      - Forta for Metamask: Forta-for-Metamask.md
      - Forta URL Authenticator: forta-chrome.md
      - Network Overview: network-overview.md
      - Run a Node:
          - Guide:
              - Introduction: scan-node/introduction.md
              - Machine setup: scan-node/machine-setup.md
              - Install Forta node: scan-node/install-forta-node.md
              - Configure: scan-node/configure.md
              - Register: scan-node/register.md
              - Run: scan-node/run.md
              - Troubleshoot: scan-node/troubleshoot.md
              - Monitor: scan-node/monitor.md
              - Upgrade: scan-node/upgrade.md
              - FAQ: scan-node/faq.md
              - Miscellaneous: scan-node/miscellaneous.md
          - Local mode: scanner-local-mode.md
          - Monitoring SLA:
              - SLA Score Calculation: sla.md
              - SLA API: sla-api.md
          - Manage pools and stake: scanner-pools.md
          - Node Resources:
              - Scan with Alchemy: alchemy-partnership.md
              - Scan with Chainstack: scan-with-chainstack.md
              - Scan with Bware: bware-partnership.md
              - Scan with Quicknode: quicknode-partnership.md
      - Network Fees and Developer Rewards:
          - Why Fees?: fees-why.md
          - Tutorial | How to Pay for Forta: fees-tut-how-pay.md
          - Tutorial | How to earn developing on Forta: fees-tut-how-earn.md
          - FAQs about fees: fees-faqs.md
      - Build on Forta:
          - Introduction to Bot Development: intro-to-bot-dev.md
          - Migrating from v1 SDK: migrating-from-v1.md
          - Develop a Bot with the v2 SDK:
              - 1) Quick start: quickstart.md
              - 2) Testing your bot: testing.md
              - 3) Deploying your bot: deploying.md
              - 4) Subscribing to alerts: subscribing.md
              - 5) Maintaining your bot: maintaining.md
              - Tools:
                  - Useful libraries: useful-libraries.md
                  - Javascript/Typescript SDK: sdk.md
                  - Python SDK: python.md
                  - CLI commands: cli.md
                  - forta.config.json: config.md
                  - Video tutorials: tutorials.md
                  - Integrating with Hardhat: hardhat.md
                  - CLI Reference: deploying-cli.md
              - Develop a Bot with Bot Wizard: wizard.md
              - Bot Examples: https://github.com/forta-network/forta-bot-examples
              - Bot Development Patterns:
                  - Index: bot-development-patterns.md
                  - Best Practices: best-practices.md
                  - Adding labels to findings: labels.md
                  - Error monitoring: error-monitoring.md
                  - Increasing bot throughput: sharding.md
                  - Long running tasks: long-running-tasks.md
                  - Protecting sensitive data: sensitive-data.md
                  - Private alerts: private-alerts.md
                  - JWT authentication for bots: jwt-auth.md
                  - External bots: external-bots.md
                  - Deploying machine learning models: deploying-ml-models.md
                  - Time series analysis: time-series-analysis.md
                  - Consuming bot alerts: handle-alert.md
                  - Transfer Bot Ownership: bot-transfer-ownership.md
                  - Transaction simulation: tx-simulation.md
                  - Advanced testing: advanced-testing.md
                  - Querying other chains: querying-chains.md
                  - Bot Licensing: bot-licensing.md
                  - Bot Development Contests:
                      - Compound Contest (10/20/2021): contest1-compound.md
                      - Aave Contest (11/3/2021): contest2-aave.md
                      - OpenZeppelin Contest (11/18/2021): contest3-oz.md
                      - Forta Contest (12/17/2021): contest4-forta.md
                      - Solace Contest (3/1/2022): contest5-solace.md
                      - Forta Contest 2 (4/27/2022): contest6-forta.md
                      - Forta Contest 3 (6/17/2022): contest7-forta.md
                      - Forta Contest 4 (8/31/2022): contest8-forta.md
                      - Forta Contest 5 (10/11/2022): contest9-forta.md
                      - Forta Contest 6 (11/8/2022): contest10-forta.md
          - Machine Learning on Forta:
              - Why Machine Learning?: ml-with-forta.md
              - Datasets and Resources: ml-data-resources.md
          - Tutorial | How to earn developing on Forta: fees-tut-how-earn.md

              
      

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: blue grey
  logo: forta-logo.png
  favicon: forta-logo.png
  features:
    - navigation.instant
    - navigation.top

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FortaNetwork
      name: Forta on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KACdTEutQq
      name: Forta on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/forta-network
      name: Forta on Github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_jxKtYfj7iLn4hTpQmBcYA
      name: Forta on YouTube
    - icon: fontawesome/solid/rss
      link: https://forta.org/blog/
      name: Forta Blog
    - icon: fontawesome/solid/envelope
      link: mailto:community@forta.org

extra_css:
  - stylesheets/extra.css
