site_name: Forta Docs

nav:
  - <strong>Receive Forta Alerts</strong>:
      - Getting started: receive-forta-alerts.md
      - Curated Feeds:
          - Attack Detector Feed: attack-detector-feed.md
          - Suspicious Events Feed: suspicious-events-feed.md
      - Access real-time alerts with GraphQL:
          - API Access: api.md
          - GraphQL API reference: forta-api-reference/index.html
          - Example use cases: api-example-use-cases.md
          - Example queries & tutorials: api-examples-tutorials.md
      - Access historical alerts with SQL:
          - Luabase Access: luabase-access.md
          - Example SQL queries & tutorials: luabase-examples-tutorials.md
  - <strong>Build Detection Bots</strong>:
      - Getting started: getting-started.md
      - Build your first detection bot:
          - 1) Quick start: quickstart.md
          - 2) Testing your bot: testing.md
          - 3) Deploying your bot: deploying.md
          - 4) Subscribing to alerts: subscribing.md
          - 5) Maintaining your bot: maintaining.md
          - Best practices: best-practices.md
          - Video tutorials: tutorials.md
      - Detection bot wizard: wizard.md
      - Bot development patterns:
          - Protecting sensitive data: sensitive-data.md
          - JWT authentication for bots: jwt-auth.md
          - Private alerts: private-alerts.md
          - Transaction simulation: tx-simulation.md
          - Long running tasks: long-running-tasks.md
          - Querying other chains: querying-chains.md
          - Error monitoring: error-monitoring.md
          - Advanced testing: advanced-testing.md
          - Time series analysis: time-series-analysis.md
          - Deploying machine learning models: deploying-ml-models.md
      - Tools:
          - Useful libraries: useful-libraries.md
          - Javascript/Typescript SDK: sdk.md
          - Python SDK: python.md
          - CLI commands: cli.md
          - forta.config.json: config.md
      - Stake on your Bot: stake-on-detection-bot.md
      - Bot developer contests:
          - Compound Contest (10/20/2021): contest1-compound.md
          - Aave Contest (11/3/2021): contest2-aave.md
          - OpenZeppelin Contest (11/18/2021): contest3-oz.md
          - Forta Contest (12/17/2021): contest4-forta.md
          - Solace Contest (3/1/2022): contest5-solace.md
          - Forta Contest 2 (4/27/2022): contest6-forta.md
          - Forta Contest 3 (6/17/2022): contest7-forta.md
          - Forta Contest 4 (8/31/2022): contest8-forta.md
          - Forta Contest 5 (10/11/2022): contest9-forta.md
          - Forta Contest 6 (11/8/2022): contest10-forta.md
      - Integrating with Hardhat: hardhat.md
  - <strong>Run a Scan Node</strong>:
      - Quickstart: scanner-quickstart.md
      - SLA Calculation: sla.md
      - SLA API: sla-api.md
      - Stake on your Scan Node: stake-on-scan-node.md
      - Local Scan Node: scanner-local-mode.md
      - Scan With Alchemy: alchemy-partnership.md
  - <strong>Machine Learning on Forta</strong>:
      - Intro to Machine Learning: ml-with-forta.md
      - Machine Learning on Forta: ds-and-ml.md
  - <strong>About Forta</strong>:
      - What is Forta: what-is-forta.md
      - FORT token: fort-token.md
      - Stake Slashing:
          - Slashing Policy: slashing-policy.md
          - Creating a Slash Proposal: slashing-creating-proposal.md
      - Governance: governance.md
      - Smart contracts:
          - Intro & Addresses: smart-contracts.md
          - Components:
              - Access: contracts/components/access/AccessManager.md
              - Agents (Detection Bots):
                  - AgentRegistry: contracts/components/agents/AgentRegistry.md
                  - AgentRegistryCore: contracts/components/agents/AgentRegistryCore.md
                  - AgentRegistryEnable: contracts/components/agents/AgentRegistryEnable.md
                  - AgentRegistryEnumerable: contracts/components/agents/AgentRegistryEnumerable.md
                  - AgentRegistryMetadata: contracts/components/agents/AgentRegistryMetadata.md
              - Dispatch:
                  - Dispatch: contracts/components/metatx/EIP712WithNonce.md
              - MetaTx:
                  - EIP712WithNonce: contracts/components/dispatch/Dispatch.md
                  - Forwarder: docs/contracts/components/metatx/Forwarder.md
              - Scanners:
                  - ScannerNodeVersion: contracts/components/scanners/ScannerNodeVersion.md
                  - ScannerRegistry: contracts/components/scanners/ScannerRegistry.md
                  - ScannerRegistryCore: contracts/components/scanners/ScannerRegistryCore.md
                  - ScannerRegistryEnable: contracts/components/scanners/ScannerRegistryEnable.md
                  - ScannerRegistryManaged: contracts/components/scanners/ScannerRegistryManaged.md
                  - ScannerRegistryMetadata: contracts/components/scanners/ScannerRegistryMetadata.md
              - Staking:
                  - FortaStaking: contracts/components/staking/FortaStaking.md
                  - FortaStakingParameters: contracts/components/staking/FortaStakingParameters.md
                  - FortaStakingUtils: contracts/components/staking/FortaStakingUtils.md
                  - ISlashingExecutor: contracts/components/staking/ISlashingExecutor.md
                  - IStakeController: contracts/components/staking/IStakeController.md
                  - IStakeSubject: contracts/components/staking/IStakeSubject.md
                  - SlashingController: contracts/components/staking/SlashingController.md
                  - StakeSubject: contracts/components/staking/StakeSubject.md
                  - SubjectTypes: contracts/components/staking/SubjectTypes.md
              - Utils:
                  - AccessManaged: contracts/components/utils/AccessManaged.md
                  - ForwardedContext: contracts/components/utils/ForwardedContext.md
                  - IVersioned: contracts/components/utils/IVersioned.md
                  - StateMachines: contracts/components/utils/StateMachines.md
              - BaseComponentUpgradeable: contracts/components/BaseComponentUpgradeable.md
              - Roles: contracts/components/Roles.md
              - Errors: contracts/errors/GeneralErrors.md
              - Token:
                  - Forta: contracts/token/Forta.md
                  - FortaBridgedPolygon: contracts/token/FortaBridgedPolygon.md
                  - FortaCommon: contracts/token/FortaCommon.md
              - Tools:
                  - Distributions: contracts/tools/Distributions.md
      - Security:
          - Security Overview: security.md
          - Design: security-design.md
          - Development: security-develop.md
          - Deployment: security-deploy.md
          - Testing and Review: security-testing.md
          - Maintenance: security-maintain.md
      - How to contribute: contributing.md
      - FAQ: faq.md

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: blue grey
  logo: forta-logo.png
  favicon: forta-logo.png
  features:
    - navigation.instant
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FortaNetwork
      name: Forta on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/tpWYdjyc6Q
      name: Forta on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/forta-network
      name: Forta on Github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_jxKtYfj7iLn4hTpQmBcYA
      name: Forta on YouTube
    - icon: fontawesome/solid/rss
      link: https://forta.org/blog/
      name: Forta Blog
    - icon: fontawesome/solid/envelope
      link: mailto:community@forta.org

extra_css:
  - stylesheets/extra.css
